/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

//import Connect.DM_Connect;
import Connect.DM_Connect;

//import Model.DM;
import Model.DM;

import java.awt.Toolkit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class QuanLyDM extends javax.swing.JFrame {

    private DefaultTableModel dtmDM;
    private ArrayList<DM> dsnxbs = null;
    private ArrayList<DM> dsnxb_tim = null;

    /**
     * Creates new form QuanLyDM
     */
    public QuanLyDM(String title) {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("images/books_30px.png"));
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lý Danh Mục");
        hienThiToanBoDanhMuc();
    }

    private void hienThiToanBoDanhMuc() {
        DM_Connect nxb_conn = new DM_Connect();
        dsnxbs = nxb_conn.layToanBoDanhMuc();
        dtmDM = new DefaultTableModel();
        dtmDM.addColumn("Mã danh mục");
        dtmDM.addColumn("Tên danh mục");
        dtmDM.addColumn("Mô tả");
        dsnxbs = nxb_conn.layToanBoDanhMuc();
        dtmDM.setRowCount(0);
        for (DM nxb : dsnxbs) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(nxb.getMaDM());
            vec.add(nxb.getTenDM());
            vec.add(nxb.getMoTa());
            dtmDM.addRow(vec);
        }
        DanhMucTable.setModel(dtmDM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DanhMucTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        MaDMLabel = new javax.swing.JLabel();
        MaDMBInput = new javax.swing.JTextField();
        TenDMLabel = new javax.swing.JLabel();
        TenDMInput = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        MoTaLabel = new javax.swing.JLabel();
        MoTaInput = new javax.swing.JTextField();
        TimDanhMucLabel = new javax.swing.JLabel();
        ThongTinDanhMucLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TKDMBtn = new javax.swing.JButton();
        AllDMBtn = new javax.swing.JButton();
        TimKiemInput = new javax.swing.JTextField();
        NhanTenLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DanhMucTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhMucTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DanhMucTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MaDMLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MaDMLabel.setText("Mã danh mục");

        TenDMLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TenDMLabel.setText("Tên danh mục");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TenDMLabel)
                    .addComponent(MaDMLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MaDMBInput, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(TenDMInput))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaDMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaDMBInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenDMLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TenDMInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        AddBtn.setText("Thêm");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("Cập nhật");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        ResetBtn.setText("Nhập lại");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Xóa");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        MoTaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MoTaLabel.setText("Mô tả");

        MoTaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MoTaInputKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(MoTaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MoTaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MoTaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MoTaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TimDanhMucLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TimDanhMucLabel.setForeground(new java.awt.Color(255, 0, 0));
        TimDanhMucLabel.setText("Tìm danh mục");

        ThongTinDanhMucLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ThongTinDanhMucLabel.setForeground(new java.awt.Color(255, 0, 0));
        ThongTinDanhMucLabel.setText("Thông tin danh mục");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TKDMBtn.setText("Tìm kiếm");
        TKDMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKDMBtnActionPerformed(evt);
            }
        });

        AllDMBtn.setText("Tất cả");
        AllDMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllDMBtnActionPerformed(evt);
            }
        });

        TimKiemInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemInputActionPerformed(evt);
            }
        });
        TimKiemInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TimKiemInputKeyPressed(evt);
            }
        });

        NhanTenLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NhanTenLabel.setText("Nhập tên hoặc mã danh mục");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimKiemInput)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NhanTenLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TKDMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AllDMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(NhanTenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TimKiemInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TKDMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AllDMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimDanhMucLabel)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ThongTinDanhMucLabel)
                        .addGap(561, 612, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ThongTinDanhMucLabel)
                    .addComponent(TimDanhMucLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DanhMucTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhMucTableMouseClicked
        int select = DanhMucTable.getSelectedRow();
        DM_Connect dmconn = new DM_Connect();
        MaDMBInput.setText(DanhMucTable.getValueAt(select, 0) + "");
        TenDMInput.setText(DanhMucTable.getValueAt(select, 1) + "");
        MoTaInput.setText(DanhMucTable.getValueAt(select, 2) + "");


    }//GEN-LAST:event_DanhMucTableMouseClicked

    private void TKDMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKDMBtnActionPerformed
        if (TimKiemInput.getText() == null) {
            return;
        }
        String key = TimKiemInput.getText();
        DM_Connect dmconn = new DM_Connect();
        dsnxb_tim = dmconn.TimTenDMmacdinh(key);
        dtmDM.setRowCount(0);
        for (DM nxb : dsnxb_tim) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(nxb.getMaDM());
            vec.add(nxb.getTenDM());
            vec.add(nxb.getMoTa());
            dtmDM.addRow(vec);
        }
        DanhMucTable.setModel(dtmDM);
    }//GEN-LAST:event_TKDMBtnActionPerformed

    private void AllDMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllDMBtnActionPerformed
        hienThiToanBoDanhMuc();
    }//GEN-LAST:event_AllDMBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        String madm = MaDMBInput.getText();
        DM_Connect nxb_conn = new DM_Connect();
        int ret = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.OK_CANCEL_OPTION);
        if (ret == JOptionPane.OK_OPTION) {
            int active = nxb_conn.XoaDM(madm);
            if (active > 0) {
                JOptionPane.showMessageDialog(null, "Xóa thành công!");
                hienThiToanBoDanhMuc();
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        MaDMBInput.setText("");
        TenDMInput.setText("");
        MoTaInput.setText("");
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        if (MaDMBInput.getText().trim().isEmpty() || TenDMInput.getText().trim().isEmpty() || MoTaInput.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DM_Connect dm_conn = new DM_Connect();
        DM dm = new DM();
        dm.setMaDM(MaDMBInput.getText().trim());
        dm.setTenDM(TenDMInput.getText().trim());
        dm.setMoTa(MoTaInput.getText().trim());

        int ret = JOptionPane.showConfirmDialog(null, "Bạn muốn chỉnh sửa danh mục?", "Xác nhận chỉnh sửa", JOptionPane.OK_CANCEL_OPTION);
        if (ret == JOptionPane.OK_OPTION) {
            int activeUpdate = dm_conn.updateDM(dm);
            if (activeUpdate > 0) {
                JOptionPane.showMessageDialog(null, "Chỉnh sửa thành công!");
                hienThiToanBoDanhMuc();
            } else if (activeUpdate == 0) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy danh mục cần chỉnh sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Chỉnh sửa thất bại! Kiểm tra lại thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_UpdateBtnActionPerformed
    private void xuLyThemMoi(String maDM) throws ParseException {
        DM dm = new DM();
        dm.setMaDM(MaDMBInput.getText());
        dm.setTenDM(TenDMInput.getText());
        dm.setMoTa(MoTaInput.getText());
        DM_Connect nxb_conn = new DM_Connect();
        if (nxb_conn.kiemTraTonTai(maDM) == true) {
            JOptionPane.showMessageDialog(null, "Mã danh mục này đã tồn tại!");
        } else {
            int activeLuu = nxb_conn.ThemMoiDM(dm);
            if (activeLuu > 0) {
                JOptionPane.showMessageDialog(null, "Thêm mới thành công!");
                hienThiToanBoDanhMuc();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm mới thất bại!");
            }
        }
    }
    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        int ret = JOptionPane.showConfirmDialog(null, "Bạn muốn thêm danh mục này?", "xác nhận xác nhận để thêm", JOptionPane.OK_CANCEL_OPTION);
        if (ret == JOptionPane.OK_OPTION) {
            if (MaDMBInput.getText().equals("") || TenDMInput.getText().equals("") || MoTaInput.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Dữ liệu còn thiếu");
            } else {
                String maDM = MaDMBInput.getText();
                try {
                    xuLyThemMoi(maDM);
                } catch (ParseException e1) {
                    e1.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void TimKiemInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiemInputActionPerformed

    private void MoTaInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MoTaInputKeyTyped
//        char c = evt.getKeyChar();
//        if (!Character.isDigit(c) || MoTaInput.getText().length() >= 10) {
//            evt.consume(); // Ngăn chặn ký tự không hợp lệ và ngăn chặn nhập quá 4 ký tự
//        }
    }//GEN-LAST:event_MoTaInputKeyTyped

    private void TimKiemInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TimKiemInputKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            TKDMBtnActionPerformed(null);
    }//GEN-LAST:event_TimKiemInputKeyPressed

    /**
     * @param args the command line arguments
     */
    public void showWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDM("Quản lý Danh Mục").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton AllDMBtn;
    private javax.swing.JTable DanhMucTable;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField MaDMBInput;
    private javax.swing.JLabel MaDMLabel;
    private javax.swing.JTextField MoTaInput;
    private javax.swing.JLabel MoTaLabel;
    private javax.swing.JLabel NhanTenLabel;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton TKDMBtn;
    private javax.swing.JTextField TenDMInput;
    private javax.swing.JLabel TenDMLabel;
    private javax.swing.JLabel ThongTinDanhMucLabel;
    private javax.swing.JLabel TimDanhMucLabel;
    private javax.swing.JTextField TimKiemInput;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
